### ISSUE TITLE
crash with no type

### ISSUE THREAD

**Issue by paulp** [jrudolph/scalac-plugin.g8#2]
This crashes in the repl (maybe it works from the command line) because it doesn't propagate the tree type, which it probably thinks it doesn't have to because it runs after parser, but it does.  A change to "Literal(Constant("ICanHazYourStrngLiterls")) setType tree.tpe" is sufficient.

**Comment by jrudolph** [comment]
What must I do exactly to reproduce the crash you are reporting here? Does that happen for Scala 2.9 or 2.10?

**Comment by paulp** [comment]
Sorry, it's 2.10.  M4.

% m4scala -Xplugin:./target/scala-2.10/default-be5b24_2.10-0.1-SNAPSHOT.jar

```
"ICanHazYourStrngLiterls" tpe is null
    at scala.Predef$.assert(Predef.scala:162)
    at scala.tools.nsc.Global.assert(Global.scala:235)
    at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.mainTransform(UnCurry.scala:669)
    at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:114)
```

**Comment by jrudolph** [comment]
What code are you compiling? The simple examples I am trying seem to be working.

**Comment by paulp** [comment]
Any code, no code.  It crashes during repl startup for me with the given command line, unless I make the suggested change.
